[GLOBAL]
pants_version = "2.26.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]
local_cache = false
colors=true

[source]
marker_filenames = ["pyproject.toml"]

[python]
interpreter_constraints = ["==3.13.*"]

[anonymous-telemetry]
enabled = false

[isort]
args = "--profile black"

[flake8]
args = ["--max-line-length 150"]